In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import importlib
import pickle
import aux_functions as aux
importlib.reload(aux)

In [ ]:
# MONKEY = 'M08'
# MONKEY = 'M06'
# AREA = 'v4'

In [3]:
### Full cell list from a given monkey (every area, concatenated)

# dicio_cell_list = {}
# for area in ['ofc','te','teo','v4','vpa']:
#     file_path = f'cell list {MONKEY}\\cell list {area}.txt' 
#     dicio_cell_list[area] = aux.get_dataframe_cell_list(file_path)
#     print(f'{area} data read and saved')
# df_cell = pd.concat([item for item in dicio_cell_list.values()],axis=0)
# df_cell

In [10]:
dicio_cell_list = {}
for MONKEY_ in ['M08','M06']:
    # for area in ['ofc','te','teo','v4','vpa']:
    for area in ['te','teo','v4']:
        file_path = f'cell list {MONKEY_}\\cell list {area}.txt' 
        dicio_cell_list[(area,MONKEY_)] = aux.get_dataframe_cell_list(file_path)
        print(f'{area} data read and saved')
df_cell = pd.concat([item for item in dicio_cell_list.values()],axis=0)
df_cell

te data read and saved
teo data read and saved
v4 data read and saved
te data read and saved
teo data read and saved
v4 data read and saved

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,coreRFin,,RF_type,session,neuron_id
0,1,m08cat186spk033a,m08det185spk033a,-1+6,1326,TE,0.0,0.0,face,0.486370,"0,8","1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20",0,NaN,Broad Foveal,m08cat186,spk033a
1,2,m08cat186spk033b,m08det185spk033b,-1+6,1326,TE,0.0,0.0,face,0.718640,"0,2","1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20",0,NaN,Broad Foveal,m08cat186,spk033b
2,3,m08cat186spk033c,m08det185spk033c,-1+6,1326,TE,0.0,0.0,face,0.665560,"0,1,5,6,7,14,15,16,17","2,3,4,8,9,10,11,12,13,18,19,20","0,7,15",NaN,Broad Foveal,m08cat186,spk033c
3,4,m08cat186spk033d,m08det185spk033d,-1+6,1326,TE,0.0,0.0,face,1.000000,NaN,NaN,NaN,NaN,Broad Foveal,m08cat186,spk033d
4,5,m08cat186spk033z,m08det185spk033z,-1+6,1326,TE,0.0,0.0,NaN,-0.043704,NaN,NaN,NaN,NaN,Broad Foveal,m08cat186,spk033z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3075,3076,m06cat288spk127z,m06det287spk127z,+2-5,538,V4,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,Broad Foveal,m06cat288,spk127z
3076,3077,m06cat288spk128a,m06det287spk128a,+2-5,698,V4,0.0,NaN,face,0.041171,NaN,NaN,NaN,NaN,Focal Foveal,m06cat288,spk128a
3077,3078,m06cat288spk128b,m06det287spk128b,+2-5,698,V4,0.0,NaN,NaN,0.103600,NaN,NaN,NaN,NaN,Focal Foveal,m06cat288,spk128b
3078,3079,m06cat288spk128c,m06det287spk128c,+2-5,698,V4,0.0,NaN,NaN,0.046372,NaN,NaN,NaN,NaN,Focal Foveal,m06cat288,spk128c
3079,3080,m06cat288spk128z,m06det287spk128z,+2-5,698,V4,0.0,NaN,NaN,0.070168,NaN,NaN,NaN,NaN,Focal Foveal,m06cat288,spk128z

In [11]:
df_cell = df_cell[(df_cell['RF_type']=='Focal Foveal') | ~(df_cell['RFin'].isna())]
df_cell.index = range(len(df_cell.index))
df_cell

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,coreRFin,,RF_type,session,neuron_id
0,1,m08cat186spk033a,m08det185spk033a,-1+6,1326,TE,0.0,0.0,face,0.486370,"0,8","1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20",0,NaN,Broad Foveal,m08cat186,spk033a
1,2,m08cat186spk033b,m08det185spk033b,-1+6,1326,TE,0.0,0.0,face,0.718640,"0,2","1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20",0,NaN,Broad Foveal,m08cat186,spk033b
2,3,m08cat186spk033c,m08det185spk033c,-1+6,1326,TE,0.0,0.0,face,0.665560,"0,1,5,6,7,14,15,16,17","2,3,4,8,9,10,11,12,13,18,19,20","0,7,15",NaN,Broad Foveal,m08cat186,spk033c
3,6,m08cat186spk034a,m08det185spk034a,-1+6,1486,TE,0.0,NaN,house,-0.244390,NaN,NaN,NaN,NaN,Focal Foveal,m08cat186,spk034a
4,7,m08cat186spk034b,m08det185spk034b,-1+6,1486,TE,0.0,NaN,house,-0.185990,NaN,NaN,NaN,NaN,Focal Foveal,m08cat186,spk034b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6171,3074,m06cat288spk126z,m06det287spk126z,+2-5,688,V4,0.0,NaN,NaN,0.073817,NaN,NaN,NaN,NaN,Focal Foveal,m06cat288,spk126z
6172,3077,m06cat288spk128a,m06det287spk128a,+2-5,698,V4,0.0,NaN,face,0.041171,NaN,NaN,NaN,NaN,Focal Foveal,m06cat288,spk128a
6173,3078,m06cat288spk128b,m06det287spk128b,+2-5,698,V4,0.0,NaN,NaN,0.103600,NaN,NaN,NaN,NaN,Focal Foveal,m06cat288,spk128b
6174,3079,m06cat288spk128c,m06det287spk128c,+2-5,698,V4,0.0,NaN,NaN,0.046372,NaN,NaN,NaN,NaN,Focal Foveal,m06cat288,spk128c
6175,3080,m06cat288spk128z,m06det287spk128z,+2-5,698,V4,0.0,NaN,NaN,0.070168,NaN,NaN,NaN,NaN,Focal Foveal,m06cat288,spk128z

In [12]:
len(df_cell['session'].unique())

163

In [13]:
with open(f"session_data\\all_sessions.pkl", "wb") as file:
    pickle.dump(df_cell, file)

In [6]:
df_cell

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,,"0,1,2,3,5,6,7,8,9,10,11,13,14,15,18,19,20","0,1,2,3,8,9,10,11,12,13,14,16,17,18,19,20"
0,1,m08cat072spk010b,m08det071spk010b,A+2+7,946,OFC,0.0,NaN,NaN,-0.105140,NaN,NaN,Focal Foveal,m08cat072,spk010b,NaN,NaN,NaN,NaN
2,3,m08cat075spk021b,m08det074spk021b,A+2+7,980,OFC,NaN,0.0,NaN,NaN,,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18...",Peripheral,m08cat075,spk021b,NaN,NaN,NaN,NaN
5,6,m08cat081spk065b,m08det080spk065b,A+2+7,1025,OFC,0.0,NaN,NaN,0.950620,NaN,NaN,Focal Foveal,m08cat081,spk065b,NaN,NaN,NaN,NaN
7,8,m08cat084spk003a,m08det083spk003a,A-1+7,898,OFC,0.0,NaN,face,1.000000,NaN,NaN,Focal Foveal,m08cat084,spk003a,NaN,NaN,NaN,NaN
8,9,m08cat084spk003c,m08det083spk003c,A-1+7,898,OFC,0.0,NaN,face,1.000000,NaN,NaN,Focal Foveal,m08cat084,spk003c,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1808,2006,m06cat288spk091a,m06det287spk091a,+4-2,397,VPA,NaN,0.0,NaN,-0.038927,"2,3,4,5,10,11,12,13,14,15","0,1,6,7,8,9,16,17,18,19,20",Peripheral,m06cat288,spk091a,NaN,NaN,NaN,NaN
1812,2010,m06cat288spk093a,m06det287spk093a,+4-2,407,VPA,NaN,0.0,NaN,-0.039963,"2,3,4,5,10,11,12,13,14,15","0,1,7,8,9,18,19,20",Peripheral,m06cat288,spk093a,NaN,NaN,NaN,NaN
1813,2011,m06cat288spk093b,m06det287spk093b,+4-2,407,VPA,NaN,0.0,NaN,-0.058542,"2,3,4,5,6,10,11,12,13,14,15,16","0,7,81,9,17,18,19,20",Peripheral,m06cat288,spk093b,NaN,NaN,NaN,NaN
1816,2015,m06cat288spk095a,m06det287spk095a,+4-2,417,VPA,0.0,0.0,NaN,-0.040015,"0,2,3,4,5,6,10,11,12,13,14,15","1,7,8,9,16,17,18,19,20",Broad Foveal,m06cat288,spk095a,"2,3,4,5,11,12,13,14",NaN,NaN,NaN
1817,2016,m06cat288spk095b,m06det287spk095b,+4-2,417,VPA,NaN,0.0,NaN,-0.034345,"2,3,4,5,6,10,12,13,14","0,1,7,8,9,11,16,17,18,19,20",Peripheral,m06cat288,spk095b,NaN,NaN,NaN,NaN

In [16]:
# df_cell['0,1,2,3,5,6,7,8,9,10,11,13,14,15,18,19,20'].sort_values()
# df_cell['0,1,2,3,8,9,10,11,12,13,14,16,17,18,19,20'].sort_values()

810     end
0       NaN
2       NaN
5       NaN
7       NaN
       ...
1808    NaN
1812    NaN
1813    NaN
1816    NaN
1817    NaN
Name: 0,1,2,3,8,9,10,11,12,13,14,16,17,18,19,20, Length: 8132, dtype: object

In [17]:
# df_cell.loc[[607,810]]

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,,"0,1,2,3,5,6,7,8,9,10,11,13,14,15,18,19,20","0,1,2,3,8,9,10,11,12,13,14,16,17,18,19,20"
607,617,m08cat078spk040a,m08det077spk040a,+1+0,1302,TEO,0.0,0.0,NaN,-0.23944,"0,2,3,4,5,6,11,12,13,14","1,7,8,9,10,15,16,17,18,19,20",Broad Foveal,m08cat078,spk040a,"4,5,12",NaN,NaN,NaN
607,608,m06cat198spk030a,m06det197spk030a,-2+5,528,OFC,0.0,NaN,face,0.27712,NaN,NaN,Focal Foveal,m06cat198,spk030a,NaN,NaN,NaN,NaN
607,769,m06cat069spk049a,m06det068spk049a,+1+2,1220,TEO,0.0,0.0,face,0.11943,"0,4,5,6,14","1,2,3,7,8,9,10,11,12,13,15,16,17,18,19,20",Broad Foveal,m06cat069,spk049a,"0,4,6",NaN,NaN,NaN
607,704,m06cat225spk068b,m06det224spk068b,+3+1,602,VPA,NaN,0.0,NaN,NaN,RFout,NaN,Peripheral,m06cat225,spk068b,NaN,NaN,end,NaN
810,895,m08cat255spk046c,m08det254spk046c,-1+5,1406,TE,0.0,NaN,face,1.00000,NaN,NaN,Focal Foveal,m08cat255,spk046c,NaN,NaN,NaN,NaN
810,811,m06cat267spk018a,m06det266spk018a,-2+4,827,OFC,0.0,NaN,face,1.00000,NaN,NaN,Focal Foveal,m06cat267,spk018a,NaN,NaN,NaN,NaN
810,1025,m06cat075spk097a,m06det074spk097a,+2+0,810,TEO,0.0,NaN,NaN,0.07981,NaN,NaN,Focal Foveal,m06cat075,spk097a,NaN,NaN,NaN,NaN
810,811,m06cat159spk115a,m06det158spk115a,+3-2,775,V4,0.0,NaN,NaN,0.01856,NaN,NaN,Focal Foveal,m06cat159,spk115a,NaN,NaN,NaN,NaN
810,940,m06cat237spk091a,m06det236spk091a,+4+0,559,VPA,NaN,0.0,house,NaN,RFout,NaN,Peripheral,m06cat237,spk091a,NaN,NaN,NaN,end

In [ ]:
# OR just an area

# input(f'saving only {AREA} data. ok?')
# df_cell = aux.get_dataframe_cell_list(f'cell list {MONKEY}\\cell list {AREA}.txt')
# df_cell

In [60]:
df_v4tot = df_cell[df_cell['brain_area']=='V4']
df_v4fov = df_v4tot[df_v4tot['RF_type'] == 'Focal Foveal']
df_v4broadfov = df_v4tot[df_v4tot['RF_type'] == 'Broad Foveal']
df_v4perif = df_v4tot[df_v4tot['RF_type'] == 'Peripheral']


df_TEtot = df_cell[df_cell['brain_area']=='TE']
df_TEfov = df_TEtot[df_TEtot['RF_type'] == 'Focal Foveal']
df_TEbroadfov = df_TEtot[df_TEtot['RF_type'] == 'Broad Foveal']
df_TEperif = df_TEtot[df_TEtot['RF_type'] == 'Peripheral']

df_TEOtot = df_cell[df_cell['brain_area']=='TEO']
df_TEOfov = df_TEOtot[df_TEOtot['RF_type'] == 'Focal Foveal']
df_TEObroadfov = df_TEOtot[df_TEOtot['RF_type'] == 'Broad Foveal']
df_TEOperif = df_TEOtot[df_TEOtot['RF_type'] == 'Peripheral']

In [ ]:
# df_v4 = df_cell[df_cell['brain_area']=='V4']
# df_fov = df_v4[df_v4['RF_type'] == 'Focal Foveal']
# df_nfov = df_v4[df_v4['RF_type'] != 'Focal Foveal']
# df_broadfov = df_v4[df_v4['RF_type'] == 'Broad Foveal']
# df_perif = df_v4[df_v4['RF_type'] == 'Peripheral']
# df_fov


# df_fov = df_cell[df_cell['RF_type'] == 'Focal Foveal']
# df_nfov = df_cell[df_cell['RF_type'] != 'Focal Foveal']
# df_fov

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,
2,3,m08cat120spk033c,m08det119spk033c,+3+1,660,V4,0.0,NaN,house,-0.382790,NaN,NaN,Focal Foveal,m08cat120,spk033c,NaN,NaN
3,4,m08cat120spk033z,m08det119spk033z,+3+1,660,V4,0.0,NaN,face,0.243480,NaN,NaN,Focal Foveal,m08cat120,spk033z,NaN,NaN
54,55,m08cat129spk098a,m08det128spk098a,+3-4,1110,V4,0.0,NaN,face,0.075061,NaN,NaN,Focal Foveal,m08cat129,spk098a,NaN,NaN
55,56,m08cat129spk098z,m08det128spk098z,+3-4,1110,V4,0.0,NaN,NaN,0.071743,NaN,NaN,Focal Foveal,m08cat129,spk098z,NaN,NaN
60,61,m08cat129spk100a,m08det128spk100a,+3-4,1130,V4,0.0,NaN,face,0.151440,NaN,NaN,Focal Foveal,m08cat129,spk100a,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2262,2263,m08cat261spk127a,m08det260spk127a,+3-3,876,V4,0.0,NaN,face,0.103660,NaN,NaN,Focal Foveal,m08cat261,spk127a,NaN,NaN
2263,2264,m08cat261spk127b,m08det260spk127b,+3-3,876,V4,0.0,NaN,face,0.210830,NaN,NaN,Focal Foveal,m08cat261,spk127b,NaN,NaN
2264,2265,m08cat261spk127z,m08det260spk127z,+3-3,876,V4,0.0,NaN,face,0.111990,NaN,NaN,Focal Foveal,m08cat261,spk127z,NaN,NaN
2265,2266,m08cat261spk128a,m08det260spk128a,+3-3,1036,V4,0.0,NaN,face,0.206670,NaN,NaN,Focal Foveal,m08cat261,spk128a,NaN,NaN
2266,2267,m08cat261spk128z,m08det260spk128z,+3-3,1036,V4,0.0,NaN,face,0.286230,NaN,NaN,Focal Foveal,m08cat261,spk128z,NaN,NaN

In [ ]:
# df_qtd_neurons = pd.DataFrame({'Non Foveal': df_nfov['session'].value_counts(), 'Foveal': df_fov['session'].value_counts(),'Total':df_v4['session'].value_counts()}).fillna(0).sort_values('Foveal',ascending=False)
# df_qtd_neurons = pd.DataFrame({'Broad Foveal': df_broadfov['session'].value_counts(), 'Foveal': df_fov['session'].value_counts(),'Peripheral':df_perif['session'].value_counts(),'Total':df_v4['session'].value_counts()}).fillna(0).sort_values('Foveal',ascending=False)
# df_qtd_neurons['Pct Foveal'] = 100 * df_qtd_neurons['Foveal'] / df_qtd_neurons['Total']
# df_qtd_neurons[df_qtd_neurons['Foveal']>=4]
# df_qtd_neurons[df_qtd_neurons['Foveal']>=4]

In [21]:

# df_qtd_neurons_TE = pd.DataFrame({'Broad Foveal': df_TEbroadfov['session'].value_counts(), 'Foveal': df_TEfov['session'].value_counts(),'Peripheral':df_TEperif['session'].value_counts(),'Total':df_TEtot['session'].value_counts()}).fillna(0).sort_values('Foveal',ascending=False)
# df_qtd_neurons_TEO = pd.DataFrame({'Broad Foveal': df_TEObroadfov['session'].value_counts(), 'Foveal': df_TEOfov['session'].value_counts(),'Peripheral':df_TEOperif['session'].value_counts(),'Total':df_TEOtot['session'].value_counts()}).fillna(0).sort_values('Foveal',ascending=False)
# df_qtd_neurons_TE

In [61]:
df_qtd_neurons = pd.DataFrame({'V4 Broad Foveal': df_v4broadfov['session'].value_counts(), 'V4 Foveal': df_v4fov['session'].value_counts(),'V4 Peripheral':df_v4perif['session'].value_counts(),'V4 Total':df_v4tot['session'].value_counts(),
                               'TE Broad Foveal': df_TEbroadfov['session'].value_counts(), 'TE Foveal': df_TEfov['session'].value_counts(),'TE Peripheral':df_TEperif['session'].value_counts(),'TE Total':df_TEtot['session'].value_counts(),
                               'TEO Broad Foveal': df_TEObroadfov['session'].value_counts(), 'TEO Foveal': df_TEOfov['session'].value_counts(),'TEO Peripheral':df_TEOperif['session'].value_counts(),'TEO Total':df_TEOtot['session'].value_counts(),
                               }).fillna(0).sort_values('V4 Foveal',ascending=False)
df_qtd_neurons['IT Total'] = df_qtd_neurons['TE Total']+df_qtd_neurons['TEO Total']
df_qtd_neurons

,V4 Broad Foveal,V4 Foveal,V4 Peripheral,V4 Total,TE Broad Foveal,TE Foveal,TE Peripheral,TE Total,TEO Broad Foveal,TEO Foveal,TEO Peripheral,TEO Total,IT Total
m08cat255,0.0,87.0,0.0,87.0,8.0,87.0,0.0,95.0,0.0,0.0,0.0,0.0,95.0
m08cat252,0.0,66.0,0.0,66.0,22.0,39.0,1.0,62.0,0.0,0.0,0.0,0.0,62.0
m06cat279,0.0,65.0,0.0,65.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
m08cat261,0.0,60.0,0.0,60.0,2.0,53.0,0.0,55.0,0.0,0.0,0.0,0.0,55.0
m08cat258,0.0,57.0,0.0,57.0,2.0,43.0,0.0,45.0,0.0,0.0,0.0,0.0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
m08cat037,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,7.0,5.0,24.0,24.0
m08cat034,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,8.0,2.0,25.0,25.0
m08cat030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,18.0,3.0,35.0,35.0
m08cat027,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,12.0,0.0,18.0,18.0
m06cat003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,6.0

In [62]:
df_qtd_neurons[df_qtd_neurons['TEO Total']>0].sort_values('TE Total')

,V4 Broad Foveal,V4 Foveal,V4 Peripheral,V4 Total,TE Broad Foveal,TE Foveal,TE Peripheral,TE Total,TEO Broad Foveal,TEO Foveal,TEO Peripheral,TEO Total,IT Total
m08cat129,0.0,48.0,0.0,48.0,0.0,0.0,0.0,0.0,6.0,0.0,7.0,13.0,13.0
m06cat123,0.0,0.0,22.0,22.0,0.0,0.0,0.0,0.0,1.0,11.0,1.0,13.0,13.0
m06cat105,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,3.0,2.0,27.0,27.0
m06cat102,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,22.0,2.0,42.0,42.0
m06cat099,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.0,21.0,0.0,44.0,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
m08cat135,0.0,0.0,43.0,43.0,0.0,0.0,0.0,0.0,16.0,0.0,9.0,25.0,25.0
m08cat144,0.0,0.0,16.0,16.0,0.0,0.0,0.0,0.0,32.0,0.0,0.0,32.0,32.0
m08cat114,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,4.0,10.0,51.0,51.0
m08cat159,0.0,1.0,5.0,6.0,0.0,0.0,0.0,0.0,31.0,1.0,0.0,32.0,32.0
m06cat003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,6.0

In [63]:
print(len(df_qtd_neurons[(df_qtd_neurons['IT Total']>0) & (df_qtd_neurons['V4 Total']>0)].index))
print(len(df_qtd_neurons[(df_qtd_neurons['TE Total']>0) & (df_qtd_neurons['V4 Total']>0)].index))
print(len(df_qtd_neurons[(df_qtd_neurons['TEO Total']>0) & (df_qtd_neurons['V4 Total']>0)].index))

53
20
33

In [83]:
# df_qtd_neurons[(df_qtd_neurons['TE Total']>0) & (df_qtd_neurons['V4 Total']>0)][['V4 Peripheral','TE Foveal']]
print(len(df_qtd_neurons[(df_qtd_neurons['TE Foveal']>3) & (df_qtd_neurons['V4 Peripheral']>3)][['V4 Peripheral','TE Foveal']].index))
df_qtd_neurons[(df_qtd_neurons['TE Foveal']>3) & (df_qtd_neurons['V4 Peripheral']>3)][['V4 Peripheral','TE Foveal']]

9

           V4 Peripheral  TE Foveal
m08cat204            8.0       38.0
m08cat195           15.0       69.0
m08cat201           14.0       59.0
m08cat198           23.0       31.0
m08cat210            5.0       18.0
m08cat207            6.0       35.0
m08cat192           11.0       66.0
m08cat189           10.0       70.0
m08cat186           31.0       35.0

In [84]:
# df_qtd_neurons[(df_qtd_neurons['TEO Total']>0) & (df_qtd_neurons['V4 Total']>0)][['V4 Peripheral','TEO Foveal']]
print(len(df_qtd_neurons[(df_qtd_neurons['TEO Foveal']>3) & (df_qtd_neurons['V4 Peripheral']>3)][['V4 Peripheral','TEO Foveal']].index))
df_qtd_neurons[(df_qtd_neurons['TEO Foveal']>3) & (df_qtd_neurons['V4 Peripheral']>3)][['V4 Peripheral','TEO Foveal']]

9

           V4 Peripheral  TEO Foveal
m06cat126           16.0         7.0
m06cat147           20.0         5.0
m06cat135           14.0         8.0
m06cat144           22.0        13.0
m06cat138           20.0         6.0
m06cat150           27.0        16.0
m06cat123           22.0        11.0
m06cat141           27.0         9.0
m06cat153           24.0         7.0

In [79]:
# print(len(df_qtd_neurons[(df_qtd_neurons['V4 Foveal']>0) & (df_qtd_neurons['V4 Peripheral']>0)][['V4 Peripheral','V4 Foveal']].index))
# df_qtd_neurons[(df_qtd_neurons['V4 Foveal']>0) & (df_qtd_neurons['V4 Peripheral']>0)][['V4 Peripheral','V4 Foveal']]

In [85]:
print(len(df_qtd_neurons[(df_qtd_neurons['V4 Foveal']>3) & (df_qtd_neurons['V4 Peripheral']>3)][['V4 Peripheral','V4 Foveal']].index))
df_qtd_neurons[(df_qtd_neurons['V4 Foveal']>3) & (df_qtd_neurons['V4 Peripheral']>3)][['V4 Peripheral','V4 Foveal']]
# df_qtd_neurons[(df_qtd_neurons['V4 Foveal']>0) & (df_qtd_neurons['V4 Peripheral']>0)][['V4 Peripheral','V4 Foveal']]

24

           V4 Peripheral  V4 Foveal
m06cat231           13.0       33.0
m06cat177           17.0       31.0
m06cat261            7.0       29.0
m06cat180            7.0       29.0
m06cat255            7.0       27.0
m08cat240            4.0       24.0
m06cat264           16.0       24.0
m06cat249            9.0       22.0
m06cat234           12.0       20.0
m08cat204            8.0       16.0
m08cat156            7.0       15.0
m06cat126           16.0       15.0
m08cat246            6.0       12.0
m08cat195           15.0       11.0
m06cat246           22.0       10.0
m06cat240            7.0        9.0
m06cat147           20.0        8.0
m06cat132           18.0        7.0
m06cat135           14.0        7.0
m08cat201           14.0        6.0
m08cat234           15.0        5.0
m06cat273            4.0        4.0
m08cat198           23.0        4.0
m06cat243           23.0        4.0

In [ ]:
# SESSION = 'm08cat255'
# SESSION = 'm08cat252'
# SESSION = 'm08cat261'
# SESSION = 'm08cat129'
# SESSION = 'm08cat156'

# SESSION = "m06cat279"
# SESSION = "m06cat210"
# SESSION = "m06cat192"

In [ ]:
# input(f'saving only {SESSION} data and ONLY FOVEAL. ok?')
# df_session = df_fov[df_fov['session']==SESSION]
# df_session

In [56]:
df_session = df_cell[df_cell['session']==SESSION]
print(df_session['brain_area'].value_counts())
df_session.index = pd.Index(range(len(df_session.index)))
df_session

V4     87
VPA    52
Name: brain_area, dtype: int64

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,"0,1,2,3,5,6,7,8,9,10,11,13,14,15,18,19,20","0,1,2,3,8,9,10,11,12,13,14,16,17,18,19,20"
0,1398,m06cat192spk097a,m06det191spk097a,+3-7,241,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m06cat192,spk097a,NaN,NaN,NaN
1,1399,m06cat192spk097b,m06det191spk097b,+3-7,241,V4,NaN,0.0,NaN,0.302960,6,"0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,1...",Peripheral,m06cat192,spk097b,NaN,NaN,NaN
2,1400,m06cat192spk097z,m06det191spk097z,+3-7,241,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m06cat192,spk097z,NaN,NaN,NaN
3,1401,m06cat192spk098a,m06det191spk098a,+3-7,401,V4,0.0,NaN,house,-0.039441,NaN,NaN,Focal Foveal,m06cat192,spk098a,NaN,NaN,NaN
4,1402,m06cat192spk098b,m06det191spk098b,+3-7,401,V4,0.0,NaN,NaN,0.108700,NaN,NaN,Focal Foveal,m06cat192,spk098b,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,190,m06cat192spk093a,m06det191spk093a,+3+0,391,VPA,0.0,0.0,NaN,0.072759,"0,2,3,4,5,10,11,12,13,14","1,6,7,8,9,15,16,17,18,19,20",Broad Foveal,m06cat192,spk093a,"2,3,4,5,10,11,12,13,14",NaN,NaN
135,191,m06cat192spk093b,m06det191spk093b,+3+0,391,VPA,NaN,0.0,house,-0.451600,"12,13,3,4,11","0,1,2,5,6,7,8,9,10,14,15,16,17,18,19,20",Peripheral,m06cat192,spk093b,NaN,NaN,NaN
136,193,m06cat192spk095a,m06det191spk095a,+3+0,401,VPA,NaN,0.0,house,-0.341630,"4,13,10,11,12,3","0,6,1,2,5,7,8,9,14,15,16,17,18,19,20",Peripheral,m06cat192,spk095a,NaN,NaN,NaN
137,194,m06cat192spk095z,m06det191spk095z,+3+0,401,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m06cat192,spk095z,NaN,NaN,NaN
138,195,m06cat192spk096a,m06det191spk096a,+3+0,561,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m06cat192,spk096a,NaN,NaN,NaN

In [57]:
with open(f"session_data\\{SESSION}.pkl", "wb") as file:
    pickle.dump(df_session, file)

In [ ]:
# df_session = df_session[df_session['brain_area']=='V4']

In [ ]:
# path_destiny = f'dados\\{MONKEY}_neurons\\neurons sorted'
# list_neuron_ids = df_session['search']
# list_prefered_cat = df_session['prefer']
# list_brain_area = df_session['brain_area']
# list_RF_type = df_session['RF_type']

# # OBS: spike times here stop in the END OF THE FIRST FIX!!! We can alter later for posterior analysis.
# df_trials = aux.get_df_trials(list_neuron_ids, path_destiny, list(list_prefered_cat), list(list_brain_area), list(list_RF_type), firings_cue_and_array=True)
# df_trials

In [59]:
# sacc_start	start_first_fix	end_first_fix
# plt.hist(df_trials['start_first_fix'] - df_trials['sacc_start'], bins=np.arange(-0.05,0.1,0.01),cumulative=False,density=True)
# plt.hist(df_trials['end_first_fix']-df_trials['start_first_fix'] , bins=np.arange(-0.2,0.5,0.01),cumulative=False,density=True)